### ISSUE TITLE
Optional Modpack Mods

### ISSUE THREAD

**Issue by Confusman** [MineInAbyss/launchy#2]
### For the lightly discussed custom and optional modpack

**Base Mods**
-Fabric > [https://fabricmc.net/] duh
-Fabtic API > [https://www.curseforge.com/minecraft/mc-mods/fabric-api] more duh
-Mod Menu > [https://www.curseforge.com/minecraft/mc-mods/modmenu] also duh 
-Indium > [https://www.curseforge.com/minecraft/mc-mods/indium] basically lets other mods have more control of rendering
-Cloth Config > [https://www.curseforge.com/minecraft/mc-mods/cloth-config] just a dependency
-Load My Resources > [https://www.curseforge.com/minecraft/mc-mods/load-my-resources-fabric] forces the modpack on start up to load specific resource packs (they also wont show up the the rp tab)
-Default Options > [https://www.curseforge.com/minecraft/mc-mods/default-options] ships modpacks with custom default keybinds to avoid players having to akwardly fiddle with conflicting binds on startup

**Graphical Mods**
-Sodium > [https://www.curseforge.com/minecraft/mc-mods/sodium] improves performance drastically
-Sodium Extra > [https://www.curseforge.com/minecraft/mc-mods/sodium-extra] adds more options to sodium, bringing it more parity to optifine
-Iris > [https://www.curseforge.com/minecraft/mc-mods/irisshaders] adds shader support
-Lamb Dynamic Lights > [https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights] adds dynamic lighting
-Colour Matic > [https://www.curseforge.com/minecraft/mc-mods/colormatic] adds custom colour support for resource packs
-Continuity > [https://www.curseforge.com/minecraft/mc-mods/continuity] adds connected texture support resource packs
-Lamb Better Grass > [https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass] adds fancy grass option from old school mcpatcher days except not shit
-Fabric Skyboxes > [https://modrinth.com/mod/fabricskyboxes] adds custom skybox support
-Farsight > [https://www.curseforge.com/minecraft/mc-mods/farsight] adds chunk caching like optifine

**Gui/Camera Mods**
-Damage Tint > [https://www.curseforge.com/minecraft/mc-mods/damage-tint] screen gets redder the more damage you've sustained
-Damage Tilt > [https://www.curseforge.com/minecraft/mc-mods/damage-tilt] tilts camera in direction of damage instead of randomly
-Logical Zoom > [https://www.curseforge.com/minecraft/mc-mods/logical-zoom] adds the zoom feature from optifine
-Camera Overhaul > [https://www.curseforge.com/minecraft/mc-mods/cameraoverhaul] makes the player movement much more immersive imo (hard to explain what it does)
-Better F3 > [https://www.curseforge.com/minecraft/mc-mods/betterf3] enables customization of the F3 menu so you can remove lots of unwanted features and force people to use ingame items like the depth meter and future navigational relics
-Inventory Movement > [https://www.curseforge.com/minecraft/mc-mods/invmove-fabric] lets you move around whilst accessing an inventory, good for the sometimes fast paced nature of the abyss
-Inventory Blur > [https://www.curseforge.com/minecraft/mc-mods/blur-fabric] blurs backgrounds whilst in inventories to help balance the movement, also looks pretty
-Smooth Swapping > [https://www.curseforge.com/minecraft/mc-mods/smooth-swapping] adds a customizable animation to moving items in the inventory, no detriment to gameplay but just a little prettier and more polished looking

**Player Mods**
-First Person Model > [https://www.curseforge.com/minecraft/mc-mods/first-person-model] enables the character to be rendered whilst in first person, really helps with immersion
-Not Enough Animations > [https://www.curseforge.com/minecraft/mc-mods/not-enough-animations] adds first person animations to the game, helps with the First Person mod
-3d Skin Layers > [https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d] makes the skins on player models actually 3d instead if floating pixels, helps with the First Person mod

**Atmospheric Mods**
-Dynamic Sound filters > [https://www.curseforge.com/minecraft/mc-mods/dynamic-sound-filters] adds sound filters to the game like reverb when in caves and occlusion
-Falling Leaves > [https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric] adds falling leaves from tree's, super pretty
-Effective > [https://www.curseforge.com/minecraft/mc-mods/effective] adds waterfall cascades, super nice in l1
-Ambient Enviroment > [https://www.curseforge.com/minecraft/mc-mods/ambient-environment] add's noise to blocks to break up large area's
-Fabulous Clouds > [https://www.curseforge.com/minecraft/mc-mods/fabulous-clouds] add's customisable cloud layers, really great for the abyss
-Drip Sounds > [https://www.curseforge.com/minecraft/mc-mods/dripsounds-fabric] add's sounds to water drips
-Presence Footsteps > [https://www.curseforge.com/minecraft/mc-mods/presence-footsteps] adds multiple sound types to footsteps, takes into account speed and changes in direction etc
-Any atmospheic sound mod > [no link as there are a couple options]
 charm, mambience, dynamic surroundings etc.. Which ever yall decide is the best fit as it's pretty subjective

**Optional Mods**
-Camera Utilities > [https://www.curseforge.com/minecraft/mc-mods/camera-utils] lets you uncouple the camer in 3rd person and change the f5 distance, really nice for photos
-Fabrishot > [https://www.curseforge.com/minecraft/mc-mods/fabrishot] lets you take uber resolution photos
-Wavey Capes > [https://www.curseforge.com/minecraft/mc-mods/waveycapes] makes capes nice n wavy for photos
-Physics mod > [https://www.curseforge.com/minecraft/mc-mods/physics-mod] immersive at times, annoying at times, looks the best for vanilla mobs as they ragdoll and can be interacted with but doesn't work for abyssal mobs
-Xaero's maps > [https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map] AND [https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap-fair-play-edition] super helpfull but kinda op and immersion breaking
-Fancy Meny > [https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric] can really tie together a modpack but requires a lot of design effort to look the part
-It's the Little Things >[https://www.curseforge.com/minecraft/mc-mods/its-the-little-things] lets the modpack customise the game icon and name
-Craft Presence > [https://www.curseforge.com/minecraft/mc-mods/craftpresence] adds a lot of options to how discord displays minecraft

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

I urge anyone who has any good mod ideas not listed to please add them to this list, I am only 1 person and have very likely missed an amazing mod

**Comment by Boy0000** [comment]
most of these are now added
