### ISSUE TITLE
Uninstalling mods when game is open crashes app

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/launchy#21]
Feels like it should just pick it up and stop the process with a popup and not fully crash

![image](https://user-images.githubusercontent.com/62521371/163868026-6ebc75b1-b065-4b22-a590-69e94ae05949.png)

*sorry for norwegian lol*

**Comment by 0ffz** [comment]
I assume it says smth about the file being in use?

**Comment by Boy0000** [comment]
The process does not have access to the file because it is used by another process
